# Generated by Django 4.0.5 on 2022-06-08 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('0', 'Open'), ('1', 'Resolve'), ('2', 'Close')], default='0', max_length=2)),
                ('t_type', models.CharField(choices=[('0', 'Bug'), ('1', 'Feature Request'), ('2', 'Test Case')], default='0', max_length=2, verbose_name='Type')),
                ('severity', models.CharField(choices=[('0', 'Low'), ('1', 'Medium'), ('2', 'High')], default='0', max_length=2)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_date', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
